const jogosDatabase = [
  { name: "GTA San Andreas", platform: "PS2", image: "https://i.imgur.com/8mbeZfO.jpeg" },
  { name: "Resident Evil 4", platform: "PS2", image: "https://i.imgur.com/K38mPhA.jpeg" },
  { name: "God of War II", platform: "PS2", image: "https://i.imgur.com/e5kPz7J.jpeg" },
  { name: "Shadow of the Colossus", platform: "PS2", image: "https://i.imgur.com/i8k3g9T.jpeg" },
  { name: "Metal Gear Solid 3", platform: "PS2", image: "https://i.imgur.com/P4w8o2L.jpeg" },
  { name: "Need for Speed Underground 2", platform: "PS2", image: "https://i.imgur.com/m9V2b6W.jpeg" },
  { name: "Devil May Cry 3", platform: "PS2", image: "https://i.imgur.com/y3n1o7T.jpeg" },
  { name: "Gran Turismo 4", platform: "PS2", image: "https://i.imgur.com/j0f9s8d.jpeg" },
  { name: "Final Fantasy X", platform: "PS2", image: "https://i.imgur.com/b2n8k4l.jpeg" },
  { name: "Bully", platform: "PS2", image: "https://i.imgur.com/c9m3v1h.jpeg" },
  { name: "Silent Hill 2", platform: "PS2", image: "https://i.imgur.com/a4s8d2f.jpeg" },
  { name: "Kingdom Hearts II", platform: "PS2", image: "https://i.imgur.com/o5p2l8k.jpeg" },
  { name: "Prince of Persia: Sands of Time", platform: "PS2", image: "https://i.imgur.com/q1w5e9r.jpeg" },
  { name: "Tekken 5", platform: "PS2", image: "https://i.imgur.com/m2n8b4v.jpeg" },
  { name: "Dragon Ball Z: Budokai Tenkaichi 3", platform: "PS2", image: "https://i.imgur.com/l3k7j9h.jpeg" },
  { name: "Okami", platform: "PS2", image: "https://i.imgur.com/t9v3r5y.jpeg" },
  { name: "Ratchet & Clank: Up Your Arsenal", platform: "PS2", image: "https://i.imgur.com/w4p8q2e.jpeg" },
  { name: "Jak 3", platform: "PS2", image: "https://i.imgur.com/u1n7m9x.jpeg" },
  { name: "Burnout 3: Takedown", platform: "PS2", image: "https://i.imgur.com/z7x9c3v.jpeg" },
  { name: "Final Fantasy XII", platform: "PS2", image: "https://i.imgur.com/p6s1d4f.jpeg" },

  // 80 jogos adicionais
  { name: "God of War", platform: "PS2", image: "https://i.imgur.com/placeholder1.jpeg" },
  { name: "Metal Gear Solid 2: Sons of Liberty", platform: "PS2", image: "https://i.imgur.com/placeholder2.jpeg" },
  { name: "Grand Theft Auto: Vice City", platform: "PS2", image: "https://i.imgur.com/placeholder3.jpeg" },
  { name: "Grand Theft Auto III", platform: "PS2", image: "https://i.imgur.com/placeholder4.jpeg" },
  { name: "Kingdom Hearts", platform: "PS2", image: "https://i.imgur.com/placeholder5.jpeg" },
  { name: "Persona 3 FES", platform: "PS2", image: "https://i.imgur.com/placeholder6.jpeg" },
  { name: "Ico", platform: "PS2", image: "https://i.imgur.com/placeholder7.jpeg" },
  { name: "Katamari Damacy", platform: "PS2", image: "https://i.imgur.com/placeholder8.jpeg" },
  { name: "Spider-Man 2", platform: "PS2", image: "https://i.imgur.com/placeholder9.jpeg" },
  { name: "SoulCalibur II", platform: "PS2", image: "https://i.imgur.com/placeholder10.jpeg" },
  { name: "TimeSplitters 2", platform: "PS2", image: "https://i.imgur.com/placeholder11.jpeg" },
  { name: "Tony Hawk's Pro Skater 3", platform: "PS2", image: "https://i.imgur.com/placeholder12.jpeg" },
  { name: "Gran Turismo 3: A-Spec", platform: "PS2", image: "https://i.imgur.com/placeholder13.jpeg" },
  { name: "Jak and Daxter: The Precursor Legacy", platform: "PS2", image: "https://i.imgur.com/placeholder14.jpeg" },
  { name: "Ratchet & Clank", platform: "PS2", image: "https://i.imgur.com/placeholder15.jpeg" },
  { name: "Sly Cooper and the Thievius Raccoonus", platform: "PS2", image: "https://i.imgur.com/placeholder16.jpeg" },
  { name: "Onimusha: Warlords", platform: "PS2", image: "https://i.imgur.com/placeholder17.jpeg" },
  { name: "Devil May Cry", platform: "PS2", image: "https://i.imgur.com/placeholder18.jpeg" },
  { name: "Final Fantasy X-2", platform: "PS2", image: "https://i.imgur.com/placeholder19.jpeg" },
  { name: "Dragon Quest VIII: Journey of the Cursed King", platform: "PS2", image: "https://i.imgur.com/placeholder20.jpeg" },
  { name: "Shin Megami Tensei: Persona 4", platform: "PS2", image: "https://i.imgur.com/placeholder21.jpeg" },
  { name: "Yakuza", platform: "PS2", image: "https://i.imgur.com/placeholder22.jpeg" },
  { name: "Ace Combat 4: Shattered Skies", platform: "PS2", image: "https://i.imgur.com/placeholder23.jpeg" },
  { name: "SSX Tricky", platform: "PS2", image: "https://i.imgur.com/placeholder24.jpeg" },
  { name: "Madden NFL 2005", platform: "PS2", image: "https://i.imgur.com/placeholder25.jpeg" },
  { name: "Pro Evolution Soccer 6", platform: "PS2", image: "https://i.imgur.com/placeholder26.jpeg" },
  { name: "Silent Hill 3", platform: "PS2", image: "https://i.imgur.com/placeholder27.jpeg" },
  { name: "Fatal Frame II: Crimson Butterfly", platform: "PS2", image: "https://i.imgur.com/placeholder28.jpeg" },
  { name: "Resident Evil Code: Veronica X", platform: "PS2", image: "https://i.imgur.com/placeholder29.jpeg" },
  { name: "Viewtiful Joe", platform: "PS2", image: "https://i.imgur.com/placeholder30.jpeg" },
  { name: "Psychonauts", platform: "PS2", image: "https://i.imgur.com/placeholder31.jpeg" },
  { name: "Black", platform: "PS2", image: "https://i.imgur.com/placeholder32.jpeg" },
  { name: "Killer7", platform: "PS2", image: "https://i.imgur.com/placeholder33.jpeg" },
  { name: "God Hand", platform: "PS2", image: "https://i.imgur.com/placeholder34.jpeg" },
  { name: "Manhunt", platform: "PS2", image: "https://i.imgur.com/placeholder35.jpeg" },
  { name: "True Crime: Streets of LA", platform: "PS2", image: "https://i.imgur.com/placeholder36.jpeg" },
  { name: "Midnight Club II", platform: "PS2", image: "https://i.imgur.com/placeholder37.jpeg" },
  { name: "Need for Speed: Most Wanted", platform: "PS2", image: "https://i.imgur.com/placeholder38.jpeg" },
  { name: "Burnout Revenge", platform: "PS2", image: "https://i.imgur.com/placeholder39.jpeg" },
  { name: "Wipeout Fusion", platform: "PS2", image: "https://i.imgur.com/placeholder40.jpeg" },
  { name: "Amplitude", platform: "PS2", image: "https://i.imgur.com/placeholder41.jpeg" },
  { name: "Guitar Hero II", platform: "PS2", image: "https://i.imgur.com/placeholder42.jpeg" },
  { name: "Dance Dance Revolution Extreme", platform: "PS2", image: "https://i.imgur.com/placeholder43.jpeg" },
  { name: "EyeToy: Play", platform: "PS2", image: "https://i.imgur.com/placeholder44.jpeg" },
  { name: "SingStar", platform: "PS2", image: "https://i.imgur.com/placeholder45.jpeg" },
  { name: "SOCOM II: U.S. Navy SEALs", platform: "PS2", image: "https://i.imgur.com/placeholder46.jpeg" },
  { name: "Medal of Honor: Frontline", platform: "PS2", image: "https://i.imgur.com/placeholder47.jpeg" },
  { name: "Call of Duty: Finest Hour", platform: "PS2", image: "https://i.imgur.com/placeholder48.jpeg" },
  { name: "Timesplitters: Future Perfect", platform: "PS2", image: "https://i.imgur.com/placeholder49.jpeg" },
  { name: "Half-Life", platform: "PS2", image: "https://i.imgur.com/placeholder50.jpeg" },
  { name: "The Getaway", platform: "PS2", image: "https://i.imgur.com/placeholder51.jpeg" },
  { name: "The Warriors", platform: "PS2", image: "https://i.imgur.com/placeholder52.jpeg" },
  { name: "Def Jam Vendetta", platform: "PS2", image: "https://i.imgur.com/placeholder53.jpeg" },
  { name: "Fight Night Round 2", platform: "PS2", image: "https://i.imgur.com/placeholder54.jpeg" },
  { name: "WWE SmackDown! Here Comes the Pain", platform: "PS2", image: "https://i.imgur.com/placeholder55.jpeg" },
  { name: "NBA Street Vol. 2", platform: "PS2", image: "https://i.imgur.com/placeholder56.jpeg" },
  { name: "Virtua Fighter 4", platform: "PS2", image: "https://i.imgur.com/placeholder57.jpeg" },
  { name: "Tekken Tag Tournament", platform: "PS2", image: "https://i.imgur.com/placeholder58.jpeg" },
  { name: "SoulCalibur III", platform: "PS2", image: "https://i.imgur.com/placeholder59.jpeg" },
  { name: "Armored Core 2", platform: "PS2", image: "https://i.imgur.com/placeholder60.jpeg" },
  { name: "Zone of the Enders", platform: "PS2", image: "https://i.imgur.com/placeholder61.jpeg" },
  { name: "Xenosaga Episode I", platform: "PS2", image: "https://i.imgur.com/placeholder62.jpeg" },
  { name: "Star Ocean: Till the End of Time", platform: "PS2", image: "https://i.imgur.com/placeholder63.jpeg" },
  { name: "Radiata Stories", platform: "PS2", image: "https://i.imgur.com/placeholder64.jpeg" },
  { name: "Suikoden V", platform: "PS2", image: "https://i.imgur.com/placeholder65.jpeg" },
  { name: "Disgaea: Hour of Darkness", platform: "PS2", image: "https://i.imgur.com/placeholder66.jpeg" },
  { name: "Shin Megami Tensei III: Nocturne", platform: "PS2", image: "https://i.imgur.com/placeholder67.jpeg" },
  { name: "Wild Arms 3", platform: "PS2", image: "https://i.imgur.com/placeholder68.jpeg" },
  { name: "Dark Cloud 2", platform: "PS2", image: "https://i.imgur.com/placeholder69.jpeg" },
  { name: "Rogue Galaxy", platform: "PS2", image: "https://i.imgur.com/placeholder70.jpeg" },
  { name: "Valkyrie Profile 2: Silmeria", platform: "PS2", image: "https://i.imgur.com/placeholder71.jpeg" },
  { name: "Dragon Ball Z: Budokai", platform: "PS2", image: "https://i.imgur.com/placeholder72.jpeg" },
  { name: "Naruto: Ultimate Ninja", platform: "PS2", image: "https://i.imgur.com/placeholder73.jpeg" },
  { name: "One Piece: Grand Battle!", platform: "PS2", image: "https://i.imgur.com/placeholder74.jpeg" },
  { name: "Crash Bandicoot: The Wrath of Cortex", platform: "PS2", image: "https://i.imgur.com/placeholder75.jpeg" },
  { name: "Spyro: Enter the Dragonfly", platform: "PS2", image: "https://i.imgur.com/placeholder76.jpeg" },
  { name: "Sly 2: Band of Thieves", platform: "PS2", image: "https://i.imgur.com/placeholder77.jpeg" },
  { name: "Jak II", platform: "PS2", image: "https://i.imgur.com/placeholder78.jpeg" },
  { name: "Ratchet & Clank: Going Commando", platform: "PS2", image: "https://i.imgur.com/placeholder79.jpeg" },
  { name: "Twisted Metal: Black", platform: "PS2", image: "https://i.imgur.com/placeholder80.jpeg" }
];
