const jogosDatabase = [
  { name: "GTA San Andreas", platform: "PS2", serial: "SLUS-20946", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20946.jpg" },
  { name: "Resident Evil 4", platform: "PS2", serial: "SLUS-21134", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21134.jpg" },
  { name: "God of War II", platform: "PS2", serial: "SCUS-97481", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97481.jpg" },
  { name: "Shadow of the Colossus", platform: "PS2", serial: "SCUS-97472", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97472.jpg" },
  { name: "Metal Gear Solid 3", platform: "PS2", serial: "SLUS-20915", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20915.jpg" },
  { name: "Need for Speed Underground 2", platform: "PS2", serial: "SLUS-20963", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20963.jpg" },
  { name: "Devil May Cry 3", platform: "PS2", serial: "SLUS-20957", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20957.jpg" },
  { name: "Gran Turismo 4", platform: "PS2", serial: "SCUS-97328", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97328.jpg" },
  { name: "Final Fantasy X", platform: "PS2", serial: "SLUS-20312", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20312.jpg" },
  { name: "Bully", platform: "PS2", serial: "SLUS-21242", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21242.jpg" },
  { name: "Silent Hill 2", platform: "PS2", serial: "SLUS-20228", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20228.jpg" },
  { name: "Kingdom Hearts II", platform: "PS2", serial: "SLUS-21005", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21005.jpg" },
  { name: "Prince of Persia: Sands of Time", platform: "PS2", serial: "SLUS-20488", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20488.jpg" },
  { name: "Tekken 5", platform: "PS2", serial: "SLUS-21059", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21059.jpg" },
  { name: "Dragon Ball Z: Budokai Tenkaichi 3", platform: "PS2", serial: "SLUS-21485", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21485.jpg" },
  { name: "Okami", platform: "PS2", serial: "SLUS-21130", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21130.jpg" },
  { name: "Ratchet & Clank: Up Your Arsenal", platform: "PS2", serial: "SCUS-97465", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97465.jpg" },
  { name: "Jak 3", platform: "PS2", serial: "SCUS-97429", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97429.jpg" },
  { name: "Burnout 3: Takedown", platform: "PS2", serial: "SLUS-20680", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20680.jpg" },
  { name: "Final Fantasy XII", platform: "PS2", serial: "SLUS-20594", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20594.jpg" },

  // 80 jogos adicionais
  { name: "God of War", platform: "PS2", serial: "SCUS-97399", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97399.jpg" },
  { name: "Metal Gear Solid 2: Sons of Liberty", platform: "PS2", serial: "SLUS-20543", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20543.jpg" },
  { name: "Grand Theft Auto: Vice City", platform: "PS2", serial: "SLUS-20552", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20552.jpg" },
  { name: "Grand Theft Auto III", platform: "PS2", serial: "SLUS-20062", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20062.jpg" },
  { name: "Kingdom Hearts", platform: "PS2", serial: "SLUS-20370", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20370.jpg" },
  { name: "Persona 3 FES", platform: "PS2", serial: "SLUS-21621", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21621.jpg" },
  { name: "Ico", platform: "PS2", serial: "SCUS-97113", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97113.jpg" },
  { name: "Katamari Damacy", platform: "PS2", serial: "SLUS-21008", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21008.jpg" },
  { name: "Spider-Man 2", platform: "PS2", serial: "SLUS-20588", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20588.jpg" },
  { name: "SoulCalibur II", platform: "PS2", serial: "SLUS-20467", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20467.jpg" },
  { name: "TimeSplitters 2", platform: "PS2", serial: "SLUS-20418", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20418.jpg" },
  { name: "Tony Hawk's Pro Skater 3", platform: "PS2", serial: "SLUS-20013", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20013.jpg" },
  { name: "Gran Turismo 3: A-Spec", platform: "PS2", serial: "SCUS-97102", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97102.jpg" },
  { name: "Jak and Daxter: The Precursor Legacy", platform: "PS2", serial: "SCUS-97124", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97124.jpg" },
  { name: "Ratchet & Clank", platform: "PS2", serial: "SCUS-97125", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97125.jpg" },
  { name: "Sly Cooper and the Thievius Raccoonus", platform: "PS2", serial: "SCUS-97198", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97198.jpg" },
  { name: "Onimusha: Warlords", platform: "PS2", serial: "SLUS-20016", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20016.jpg" },
  { name: "Devil May Cry", platform: "PS2", serial: "SLUS-20165", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20165.jpg" },
  { name: "Final Fantasy X-2", platform: "PS2", serial: "SLUS-20624", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20624.jpg" },
  { name: "Dragon Quest VIII: Journey of the Cursed King", platform: "PS2", serial: "SLUS-21223", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21223.jpg" },
  { name: "Shin Megami Tensei: Persona 4", platform: "PS2", serial: "SLUS-21621", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21621.jpg" },
  { name: "Yakuza", platform: "PS2", serial: "SLUS-21046", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21046.jpg" },
  { name: "Ace Combat 4: Shattered Skies", platform: "PS2", serial: "SLUS-20445", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20445.jpg" },
  { name: "SSX Tricky", platform: "PS2", serial: "SLUS-20336", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20336.jpg" },
  { name: "Madden NFL 2005", platform: "PS2", serial: "SLUS-21018", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21018.jpg" },
  { name: "Pro Evolution Soccer 6", platform: "PS2", serial: "SLUS-21355", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21355.jpg" },
  { name: "Silent Hill 3", platform: "PS2", serial: "SLUS-20622", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20622.jpg" },
  { name: "Fatal Frame II: Crimson Butterfly", platform: "PS2", serial: "SLUS-20725", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20725.jpg" },
  { name: "Resident Evil Code: Veronica X", platform: "PS2", serial: "SLUS-20152", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20152.jpg" },
  { name: "Viewtiful Joe", platform: "PS2", serial: "SLUS-20738", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20738.jpg" },
  { name: "Psychonauts", platform: "PS2", serial: "SLUS-21085", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21085.jpg" },
  { name: "Black", platform: "PS2", serial: "SLUS-21215", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21215.jpg" },
  { name: "Killer7", platform: "PS2", serial: "SLUS-20952", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20952.jpg" },
  { name: "God Hand", platform: "PS2", serial: "SLUS-21539", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21539.jpg" },
  { name: "Manhunt", platform: "PS2", serial: "SLUS-20631", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20631.jpg" },
  { name: "True Crime: Streets of LA", platform: "PS2", serial: "SLUS-20772", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20772.jpg" },
  { name: "Midnight Club II", platform: "PS2", serial: "SLUS-20415", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20415.jpg" },
  { name: "Need for Speed: Most Wanted", platform: "PS2", serial: "SLUS-21060", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21060.jpg" },
  { name: "Burnout Revenge", platform: "PS2", serial: "SLUS-21242", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21242.jpg" },
  { name: "Wipeout Fusion", platform: "PS2", serial: "SLUS-20269", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20269.jpg" },
  { name: "Amplitude", platform: "PS2", serial: "SCUS-97258", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97258.jpg" },
  { name: "Guitar Hero II", platform: "PS2", serial: "SLUS-21224", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21224.jpg" },
  { name: "Dance Dance Revolution Extreme", platform: "PS2", serial: "SLUS-20925", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20925.jpg" },
  { name: "SOCOM II: U.S. Navy SEALs", platform: "PS2", serial: "SCUS-97230", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97230.jpg" },
  { name: "Medal of Honor: Frontline", platform: "PS2", serial: "SLUS-20367", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20367.jpg" },
  { name: "Call of Duty: Finest Hour", platform: "PS2", serial: "SLUS-20953", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20953.jpg" },
  { name: "Timesplitters: Future Perfect", platform: "PS2", serial: "SLUS-21137", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21137.jpg" },
  { name: "The Getaway", platform: "PS2", serial: "SLUS-20493", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20493.jpg" },
  { name: "The Warriors", platform: "PS2", serial: "SLUS-20928", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20928.jpg" },
  { name: "Def Jam Vendetta", platform: "PS2", serial: "SLUS-20561", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20561.jpg" },
  { name: "Fight Night Round 2", platform: "PS2", serial: "SLUS-20949", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20949.jpg" },
  { name: "WWE SmackDown! Here Comes the Pain", platform: "PS2", serial: "SLUS-20619", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20619.jpg" },
  { name: "NBA Street Vol. 2", platform: "PS2", serial: "SLUS-20583", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20583.jpg" },
  { name: "Virtua Fighter 4", platform: "PS2", serial: "SLUS-20472", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20472.jpg" },
  { name: "Tekken Tag Tournament", platform: "PS2", serial: "SLUS-20001", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20001.jpg" },
  { name: "SoulCalibur III", platform: "PS2", serial: "SLUS-21216", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21216.jpg" },
  { name: "Armored Core 2", platform: "PS2", serial: "SLUS-20015", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20015.jpg" },
  { name: "Zone of the Enders", platform: "PS2", serial: "SLUS-20182", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20182.jpg" },
  { name: "Xenosaga Episode I", platform: "PS2", serial: "SLUS-20470", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20470.jpg" },
  { name: "Star Ocean: Till the End of Time", platform: "PS2", serial: "SLUS-20457", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20457.jpg" },
  { name: "Disgaea: Hour of Darkness", platform: "PS2", serial: "SLUS-20595", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20595.jpg" },
  { name: "Shin Megami Tensei III: Nocturne", platform: "PS2", serial: "SLUS-20611", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20611.jpg" },
  { name: "Dark Cloud 2", platform: "PS2", serial: "SLUS-20414", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20414.jpg" },
  { name: "Rogue Galaxy", platform: "PS2", serial: "SLUS-21419", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21419.jpg" },
  { name: "Dragon Ball Z: Budokai", platform: "PS2", serial: "SLUS-20555", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20555.jpg" },
  { name: "Naruto: Ultimate Ninja", platform: "PS2", serial: "SLUS-21238", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-21238.jpg" },
  { name: "Crash Bandicoot: The Wrath of Cortex", platform: "PS2", serial: "SLUS-20225", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20225.jpg" },
  { name: "Spyro: Enter the Dragonfly", platform: "PS2", serial: "SLUS-20420", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SLUS-20420.jpg" },
  { name: "Sly 2: Band of Thieves", platform: "PS2", serial: "SCUS-97271", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97271.jpg" },
  { name: "Jak II", platform: "PS2", serial: "SCUS-97265", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97265.jpg" },
  { name: "Ratchet & Clank: Going Commando", platform: "PS2", serial: "SCUS-97268", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97268.jpg" },
  { name: "Twisted Metal: Black", platform: "PS2", serial: "SCUS-97197", image: "https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/default/SCUS-97197.jpg" }
];
